insert into CLIENTES (id_clientes, nombre_cl, direccion_cl, DNI_cl) values (1, 'Rodrigo Castillo', 'Las Norias 2352', 35224567);
insert into CLIENTES (id_clientes, nombre_cl, direccion_cl, DNI_cl) values (2, 'Roberto Torres', 'Las Magnolias 252', 35004567);
insert into CLIENTES (id_clientes, nombre_cl, direccion_cl, DNI_cl) values (3, 'Maria Azteka', 'Falsa 123', 39454567);
insert into PEDIDOS (id_pedidos) values (1);
insert into PEDIDOS (id_pedidos) values (2);
insert into PEDIDOS (id_pedidos) values (3);
insert into ENTREGAS (id_entregas) values (1);
insert into ENTREGAS (id_entregas) values (2);
insert into ENTREGAS (id_entregas) values (3);
insert into EMPLEADOS (id_empleados, nombre_emp, direccion_emp, DNI_emp) values (1, 'Raul Fisto', 'Las Canarias 245', 41000632);
insert into EMPLEADOS (id_empleados, nombre_emp, direccion_emp, DNI_emp) values (2, 'Marianela Aguirre', 'Barcelona 998', 42907665);
insert into EMPLEADOS (id_empleados, nombre_emp, direccion_emp, DNI_emp) values (3, 'Jose Cobo', 'Operativo Condor 1006', 40789065);
insert into ALMACEN (id_almacen, existencia) values (1,0);
insert into ALMACEN (id_almacen, existencia) values (2,0);
insert into ALMACEN (id_almacen, existencia) values (3,0);
insert into ARTICULOS (id_articulos, nombre_art) values (1,'fideo tirabuzon');
insert into ARTICULOS (id_articulos, nombre_art) values (2,'manteca');
insert into ARTICULOS (id_articulos, nombre_art) values (3,'bizcochos');
insert into PRECIOS (id_precios, precio_venta, precio_compra, precio_act_may) values (1, 107, 90, 91.5);
insert into PRECIOS (id_precios, precio_venta, precio_compra, precio_act_may) values (2, 105, 88, 90);
insert into PRECIOS (id_precios, precio_venta, precio_compra, precio_act_may) values (3, 100, 75, 75);
insert into MAYORISTAS (id_mayoristas, nombre_may) values (1, 'malva');
insert into MAYORISTAS (id_mayoristas, nombre_may) values (2, 'diarcor');
insert into MAYORISTAS (id_mayoristas, nombre_may) values (3, 'maxiconsumo');
insert into MARCAS (id_marcas ,nombre_marcas) values (1, 'marolio');
insert into MARCAS (id_marcas ,nombre_marcas) values (2, 'serenisima');
insert into MARCAS (id_marcas ,nombre_marcas) values (3, '9 de oro');
insert into CATEGORIAS (id_categorias, nombre_cate) values (1, 'pastas');
insert into CATEGORIAS (id_categorias, nombre_cate) values (2, 'lacteos');
insert into CATEGORIAS (id_categorias, nombre_cate) values (3, 'galletas');
