CREATE schema ALMACEN;
USE ALMACEN;
CREATE TABLE CLIENTES (
id_clientes int NOT NULL,
id_pedidos int ,
nombre_cl varchar(200) NOT NULL,
direccion_cl varchar(200) NOT NULL,
DNI_cl int ,
CONSTRAINT PK_CLIENTES PRIMARY KEY (id_clientes)
);
CREATE TABLE PEDIDOS (
id_clientes int ,
id_pedidos int NOT NULL,
id_entregas int ,
id_almacen int ,
CONSTRAINT PK_PEDIDOS PRIMARY KEY (id_pedidos)
);
CREATE TABLE ENTREGAS (
id_pedidos int ,
id_entregas int NOT NULL,
id_empleados int ,
CONSTRAINT PK_CLASS PRIMARY KEY (id_entregas)
);
CREATE TABLE EMPLEADOS (
id_empleados int NOT NULL,
id_entregas int ,
nombre_emp varchar(200) ,
direccion_emp varchar(200) ,
DNI_emp int,
CONSTRAINT PK_CLASS PRIMARY KEY (id_empleados)
);
CREATE TABLE ALMACEN (
id_almacen int NOT NULL,
id_pedidos int ,
existencia int ,
id_articulos int ,
CONSTRAINT PK_CLASS PRIMARY KEY (id_almacen)
);
CREATE TABLE ARTICULOS (
id_almacen int ,
id_precios int ,
nombre_art varchar(200) NOT NULL,
id_articulos int NOT NULL,
id_marcas int ,
CONSTRAINT PK_CLASS PRIMARY KEY (id_articulos)
);
CREATE TABLE PRECIOS (
id_precios int Not NULL,
precio_venta float,
precio_compra float NOT NULL,
id_articulos int ,
precio_act_may float ,
id_mayoristas int ,
CONSTRAINT PK_CLASS PRIMARY KEY (id_precios)
);
CREATE TABLE MAYORISTAS (
id_mayoristas int NOT NULL,
nombre_may varchar(200) ,
id_precios int ,
CONSTRAINT PK_PEDIDOS PRIMARY KEY (id_mayoristas)
);
CREATE TABLE MARCAS (
nombre_marcas  varchar(200) NOT NULL,
id_categorias int ,
id_marcas int NOT NULL,
id_articulos int ,
CONSTRAINT PK_PEDIDOS PRIMARY KEY (id_marcas)
);
CREATE TABLE CATEGORIAS (
nombre_cate  varchar(200) NOT NULL,
id_categorias int NOT NULL,
id_marcas int ,
CONSTRAINT PK_PEDIDOS PRIMARY KEY (id_categorias)
);

ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_PEDIDOS FOREIGN KEY FK_CLIENTES_PEDIDOS (id_pedidos)
    REFERENCES PEDIDOS (id_pedidos);
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_CLIENTES FOREIGN KEY FK_PEDIDOS_CLIENTES (id_clientes)
    REFERENCES CLIENTES (id_clientes);
 ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_ENTREGAS FOREIGN KEY FK_PEDIDOS_ENTREGAS (id_entregas)
    REFERENCES ENTREGAS (id_entregas); 
 ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_ALMACEN FOREIGN KEY FK_PEDIDOS_ALMACEN (id_almacen)
    REFERENCES ALMACEN (id_almacen); 
ALTER TABLE ENTREGAS ADD CONSTRAINT FK_ENTREGAS_EMPLEADOS FOREIGN KEY FK_ENTREGAS_EMPLEADOS (id_empleados)
    REFERENCES EMPLEADOS (id_empleados);
ALTER TABLE ENTREGAS ADD CONSTRAINT FK_ENTREGAS_PEDIDOS FOREIGN KEY FK_ENTREGAS_PEDIDOS (id_pedidos)
    REFERENCES PEDIDOS (id_pedidos);
ALTER TABLE EMPLEADOS ADD CONSTRAINT FK_EMPLEADOS_ENTREGAS FOREIGN KEY FK_EMPLEADOS_ENTREGAS (id_entregas)
    REFERENCES ENTREGAS (id_entregas);
ALTER TABLE ALMACEN ADD CONSTRAINT FK_ALMACEN_PEDIDOS FOREIGN KEY FK_ALMACEN_PEDIDOS (id_pedidos)
    REFERENCES PEDIDOS (id_pedidos);
ALTER TABLE ALMACEN ADD CONSTRAINT FK_ALMACEN_ARTICULOS FOREIGN KEY FK_ALMACEN_ARTICULOS (id_articulos)
    REFERENCES ARTICULOS (id_articulos);
ALTER TABLE ARTICULOS ADD CONSTRAINT FK_ARTICULOS_PRECIOS FOREIGN KEY FK_ARTICULOS_PRECIOS (id_precios)
    REFERENCES PRECIOS (id_precios);
ALTER TABLE ARTICULOS ADD CONSTRAINT FK_ARTICULOS_MARCAS FOREIGN KEY FK_ARTICULOS_MARCAS (id_marcas)
    REFERENCES MARCAS (id_marcas);
ALTER TABLE ARTICULOS ADD CONSTRAINT FK_ARTICULOS_ALMACEN FOREIGN KEY FK_ARTICULOS_ALMACEN (id_almacen)
    REFERENCES ALMACEN (id_almacen);
ALTER TABLE PRECIOS ADD CONSTRAINT FK_PRECIOS_ARTICULOS FOREIGN KEY FK_PRECIOS_ARTICULOS (id_articulos)
    REFERENCES ARTICULOS (id_articulos);   
ALTER TABLE PRECIOS ADD CONSTRAINT FK_PRECIOS_MAYORISTAS FOREIGN KEY FK_PRECIOS_MAYORISTAS (id_mayoristas)
    REFERENCES MAYORISTAS (id_mayoristas);  
ALTER TABLE MAYORISTAS ADD CONSTRAINT FK_MAYORISTAS_PRECIOS FOREIGN KEY FK_MAYORISTAS_PRECIOS (id_precios)
    REFERENCES PRECIOS (id_precios); 
ALTER TABLE MARCAS ADD CONSTRAINT FK_MARCAS_CATEGORIAS FOREIGN KEY FK_MARCAS_CATEGORIAS (id_categorias)
    REFERENCES CATEGORIAS (id_categorias); 
ALTER TABLE MARCAS ADD CONSTRAINT FK_MARCAS_ARTICULOS FOREIGN KEY FK_MARCAS_ARTICULOS (id_articulos)
    REFERENCES ARTICULOS (id_articulos); 
ALTER TABLE CATEGORIAS ADD CONSTRAINT FK_CATEGORIAS_MARCAS FOREIGN KEY FK_CATEGORIAS_MARCAS (id_marcas)
    REFERENCES MARCAS (id_marcas); 
